### PR TITLE
fix-issues

### PR DESCRIPTION
**Pull request by asulwer**

### CODE REVIEW

**Comment by asulwer** [comment]
when i renamed the PR it closed it?

**Comment by RenanCarlosPereira** [comment]
No renaming a PR should not close it automatically

**Comment by asulwer** [comment]
i made some changes to the workflow, pay close attention to that, please

**Comment by RenanCarlosPereira** [comment]
> i made some changes to the workflow, pay close attention to that, please

I will please allow me a few hours, I will review it today

**Comment by asulwer** [comment]
take your time to review.  i have knocked out enough of this today or this weekend for that matter.

i want to thank you again, your assistance has been very much appreciated.

**Pull request closed without merging**
