### PR TITLE
fixed Demo project

### PR DESCRIPTION
**Pull request by asulwer**
https://github.com/asulwer/RulesEngine/issues/21

### CODE REVIEW

**Comment by asulwer** [comment]
[24](https://github.com/asulwer/RulesEngine/issues/24)

**Comment by RenanCarlosPereira** [comment]
Ah ok just the demo sulution right?

**Comment by RenanCarlosPereira** [comment]
I was thinking the entire solution was messy, I put this files there because the original ones where there in the root of csproj 😅

**Comment by RenanCarlosPereira** [comment]
Man, I wont recommend to merge this PR because you are not only changing the demo apps.

We mentioned we would make only PRs that are consistent and with a rational behind it.

**Comment by asulwer** [comment]
no its not just demo project fixed but many others as notated with linked open issues

**Comment by asulwer** [comment]
this PR has rational behind it, in my mind. there are many issues that i had fixed but with the merge were lost.

**Comment by RenanCarlosPereira** [comment]
Yes, but please open a particular PR so solve each topic, not only one to solve everything

If you want to solve code formatting that should be a particular PR for this

If you want to solve or add mode demos that should be a other PR without touching any of the sources or test folders inly the demo folder, so we can review it better.

The same applies to a new feature, in a separate PR

Thanks man, this way any new possible consumers of this library will be more comfortable to use it .

Would be great if you could put me as a reviewer the same way when I open a PR I ask you to review it

**Comment by asulwer** [comment]
1. this particular PR is in reference to the merge issues that occurred.  it is normal to have many issues resolved in a pull request.  i see it done quite often on github.  review the previous repositories changelog to see this in action.  each commit has an open issue assigned to it for reference.
2. consumers simply do not have the time to navigate our repository in depth.  does it work?  breaking changes? then lets use it. is typically the mentality of consumers.
3. yes i will make it a priority to have you as a reviewer of any PR's.  i simply got caught up in the changes.  rest assured that before any PR is merged you will have the chance to review it and anyone else that is willing

**Pull request closed without merging**
