### PR TITLE
add coverage exclusion for json converter

### PR DESCRIPTION
**Pull request by JasonBoggsAtHMSdotCom**

### CODE REVIEW

**Comment by JasonBoggsAtHMSdotCom** [comment]
Coverage is at 97% now

**Comment by RenanCarlosPereira** [comment]
hey @JasonBoggsAtHMSdotCom I dont think we should ignore the tests. 
specially for this class, I will open another PT, so you can check the tests. 

thanks

**Comment by JasonBoggsAtHMSdotCom** [comment]
I chose to ignore this class since the converter is called by System.Text.Json and it's never called by `RulesEngine` directly

**Comment by JasonBoggsAtHMSdotCom** [comment]
Closing in favor of https://github.com/asulwer/RulesEngine/pull/85

**Pull request closed without merging**
