### PR TITLE
demonstrate Actions; additional ways to use Actions have been commented out

### PR DESCRIPTION
**Pull request by asulwer**
https://github.com/asulwer/RulesEngine/issues/53

### CODE REVIEW

**Comment by asulwer** [comment]
attempting to come up with possible solutions for an issue

**Comment by RenanCarlosPereira** [comment]
Is it better to add the demo of what we have in the documentation? 

https://microsoft.github.io/RulesEngine/#outputexpression

**Comment by asulwer** [comment]
yes that is better.  i will change

**Comment by RenanCarlosPereira** [comment]
hey @asulwer this PR is to add the demo, isn't it? 
lets open another one explaining why we are adding other stuffs.

I will open a proposal PR talking about it, lets keep this one for the demo as the title says

**Comment by asulwer** [comment]
well it was in response to the [issue](https://github.com/asulwer/RulesEngine/issues/53) and grew as he added more info

**Comment by RenanCarlosPereira** [comment]
yeah, I see... if you want to maintain the ToExpando method you created, we need to cover it under the unit tests. 
so we don't reduce the code coverage 🙌

**Pull request closed without merging**
