### PR TITLE
PR: Add Unit Tests for ObjectAsPrimitiveConverter

### PR DESCRIPTION
**Pull request by RenanCarlosPereira**
This PR adds a bunch of unit tests for `ObjectAsPrimitiveConverter` to make sure it handles various JSON scenarios correctly. Here’s what’s covered:

- **Basic Types**: Checks `null`, `true`, `false`, strings, and numbers to confirm they’re converted right.
- **Array and Object Parsing**: Tests JSON arrays as `List<object>` and JSON objects as either `ExpandoObject` or `Dictionary`, depending on settings.
- **Special Number Handling**: Adds a test for unknown numbers that should return a `JsonElement` when configured.
- **Nested Structures**: Ensures nested JSON arrays and objects are parsed accurately.
- **Edge Cases**:
  - Empty arrays and objects should return empty lists/dictionaries.
  - Invalid JSON should throw a `JsonException`.
  - Tests for special property names with unusual characters or whitespace.
- **Boundary Values**: Tests big numbers to make sure we handle edge cases like max `Int32` and `Double` values correctly.

### CODE REVIEW

**Comment by JasonBoggsAtHMSdotCom** [comment]
Looks like coverage is still below the allowed threshold.

**Comment by RenanCarlosPereira** [comment]
@JasonBoggsAtHMSdotCom 
yes, Im still working on it.... checking the lines and the implementation, there some places in the code that I cant reach, maybe will never execute

**Comment by asulwer** [comment]
have either of you viewed the build warnings?  would clearing them up improve the codecoverage?  to see these build warnings, view 'files changed' in this PR and scroll past the file that is changed to see the warnings in question

**Review by asulwer — APPROVED** [review]

**Review by asulwer — APPROVED** [review]

**Comment by JasonBoggsAtHMSdotCom** [comment]
Thank you @RenanCarlosPereira and @asulwer for your work on this. Is there any chance we can get this released and pushed to Nuget ASAP please?

**Comment by asulwer** [comment]
@JasonBoggsAtHMSdotCom i am pushing an update later today

**Pull request merged**
