### PR TITLE
fix merge issue

### PR DESCRIPTION
**Pull request by RenanCarlosPereira**

### CODE REVIEW

**Comment by RenanCarlosPereira** [comment]
@asulwer please check if the build is still passing when approving PRs 😅

the previous PR conflicted, that's why

**Comment by asulwer** [comment]
please move IDemo into its own file please, separation of interests

**Comment by RenanCarlosPereira** [comment]
> please move IDemo into its own file please, separation of interests

that's done

**Review by asulwer — APPROVED** [review]
thank you for this addition

**Comment by RenanCarlosPereira** [comment]
nice, thanks.

So I found a bug, it might be related to PR #32.

Im working on a possible solution here, will explain in the next one

**Comment by asulwer** [comment]
keep me posted

**Pull request merged**
