### PR TITLE
Reverse back changes without braking changes and all fixes from the original project and add cancellation token

### PR DESCRIPTION
**Pull request by RenanCarlosPereira**

### CODE REVIEW

**Comment by RenanCarlosPereira** [comment]
Hi @asulwer,

Could you please review this PR?

I suggest removing versions 6.0.0 to 6.0.3 from the NuGet feed. Although this is generally not recommended, the versions we published do not accurately reflect our current progress.

Instead, we should generate a new version 6.0.0 from this build. All tests, including code coverage, CodeQL, and unit tests, are passing. Additionally, please note that from the original project, only 35 files have been changed.

Thank you!

**Comment by RenanCarlosPereira** [comment]
once we have this version ok and listed in nuget package we will install a tool called codeMaid, and run in the solution. 

please take a look on it: https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaid

**Comment by asulwer** [comment]
i spent most of my life dedicated to programming not being an english professor.

i had an essay prepared for you.

basically lets start from scratch?  PR's moving forward with changes?  rolling back ALL of the solutions to issues then creating PR's for each one?

**Review by asulwer — APPROVED** [review]
back to the beginning

**Comment by RenanCarlosPereira** [comment]
Nice, now generate the 6.0.0
😉

**Pull request merged**
