### PR TITLE
issue with code

### PR DESCRIPTION
**Pull request by asulwer**
https://github.com/asulwer/RulesEngine/issues/45

### CODE REVIEW

**Comment by asulwer** [comment]
not sure how to prevent the code from being used as it was.  not compile or runtime error, but behavior wasn't as expected

**Review by RenanCarlosPereira — APPROVED** [review]

**Comment by asulwer** [comment]
i was thinking about fixing the code to check the object array type for RulesParameter and direct accordingly

**Comment by RenanCarlosPereira** [comment]
We won't be able to fix it... if we do we will introduce breaking changes 🥹

**Comment by asulwer** [comment]
there were a couple of other places that were missed and fixed.

**Pull request merged**
