### PR TITLE
Introduce IDemo Interface and Automatic Execution in Program Class and code clean up in demo project

### PR DESCRIPTION
**Pull request by RenanCarlosPereira**
#### Overview
This PR introduces a new `IDemo` interface and updates the `Program` class to automatically discover and execute all classes that implement this interface. Additionally, CodeMaid and ReSharper have been used in demo project to format the codebase, ensuring consistency and adherence to coding standards.

#### Changes Introduced
1. **IDemo Interface**
   - Introduced `IDemo` interface with a `Run` method that takes an optional `CancellationToken`.
   ```csharp
   public interface IDemo
   {
       Task Run(CancellationToken cancellationToken = default);
   }
   ```

2. **Program Class Update**
   - Updated the `Program` class to use reflection for discovering and executing all implementations of the `IDemo` interface.

3. **Code Formatting**
   - Applied CodeMaid and ReSharper for code formatting. This includes organizing namespaces, formatting code, and removing unused references to ensure the codebase is clean and adheres to our coding standards.

#### Testing
- The implementation was tested with the main entry point in the `Program` class.
- Verified that the program successfully discovers and executes all implementations of `IDemo`, handling any exceptions gracefully and logging errors to the console.

### How to Test
1. Run the project.
2. Verify that the console outputs indicate successful discovery and execution of the `Run` methods of all classes implementing `IDemo`.
3. Check the elapsed time output to ensure the stopwatch functionality is working as expected.

### CODE REVIEW

**Review by asulwer — APPROVED** [review]
very nice changes

**Comment by RenanCarlosPereira** [comment]
man, you merged that with conflicts from the other PR. 

will open another one 😥

**Comment by asulwer** [comment]
where is the IDemo interface?

**Comment by RenanCarlosPereira** [comment]
you completed this PR with merge conflicts, we should not do it... before merging a PR you need to verify if the build is passing.

fixing it now, give me a sec.

**Comment by asulwer** [comment]
the merge conflicts were formatting issues.  i reviewed each file and saw no reason not to resolve the conflict.  what wasnt included and is causing the build issue is the missing IDemo interface.  that was not included in this PR.

**Comment by RenanCarlosPereira** [comment]
it was there, maybe when you resolved the conflicts it got removed. 😄
created another PR there #35

**Comment by asulwer** [comment]
i see it under program.cs.  shouldn't it be in its own file?

**Pull request merged**
